### ISSUE TITLE
Broken HE when disconnected 

### ISSUE THREAD

**Issue by iSeitan** [Valorless/HavenElytra#1]
When a player has merged his armor with elytra and disconnect, on reconnect it’s broken and can’t be unmerged and can’t fly also

It seems to happen since latest update

**Comment by Valorless** [comment]
I'm sorry this issue has occurred.
Do you know of a way which I can replicate the issue, or is it exactly as you wrote?
And if possible, could I join the server myself and try it out.
(I don't need OP, I just need HE perms and the required items ^^)

**Comment by iSeitan** [comment]
> I'm sorry this issue has occurred. Do you know of a way which I can replicate the issue, or is it exactly as you wrote? And if possible, could I join the server myself and try it out. (I don't need OP, I just need HE perms and the required items ^^)

I can let you in and give you the item to test yes!
mc.hailcraft.net

i'll give you the elytra and the armors
It seems to happen with custom elytra and custom armor
I use Oraxen and Ecoitems
with vanilla armor and elytra it doesnt seem to happens as much or even at all

**Comment by Valorless** [comment]
Thanks for letting me on, it helped me get a better picture ^^
From what I could see the items are combining as they should, but upon logging back in the other plugin turns the wings into the chestplate again. (Likely due to the NBT tags on the item from that plugin)
Which then does so you can't separate them, since separation requires the item to be an elytra.
(I checked the NBT tags on the item, and it still contains all HE tags as it should)

I honestly and I'm sorry to say this, don't think I can fix this issue.
I don't think I am skilled enough to figure out a way to prevent the other plugin from doing it's functions.

**Comment by iSeitan** [comment]
I'll try to reach out to oraxen then, thanks

**Comment by Boy0000** [comment]
Oraxen will, by default, ensure than an OraxenItem is kept up to date.
Thus when a player logs in all OraxenItems will be updated in their inventory with some exceptions
It keeps all new PDC entries, doesnt override lore and some other stuff

If you are changing the base material you could always force your item to never update though not really recommended.
```yml
myitem:
 displayname: "something idk"
 no_auto_update: true
...
 ```
 This prevents this specific item from being updated
